### ISSUE TITLE
Getting build error

### ISSUE THREAD

**Issue by kamarshad** [keenresearch/keenasr-swift-poc#1]
Hello @ognjentodic 
I am trying to use this library for Speech To Text purpose. But I am not able to build the swift POC project everytime getting the following build error.

`error: Build input file cannot be found: '/Users/mohdkamar/Library/Developer/Xcode/DerivedData/keenasr-swift-poc-glvifghsvbwsqufrainpyozcirde/Build/Products/Debug-iphonesimulator/keenasr-swift-poc.app/keenasr-swift-poc'`

`Build input file cannot be found: '/Users/mohdkamar/Library/Developer/Xcode/DerivedData/keenasr-swift-poc-glvifghsvbwsqufrainpyozcirde/Build/Products/Debug-iphonesimulator/keenasr-swift-poc.app/keenasr-swift-poc'`

Xcode version: `10.1`

Any idea how can I resolve the build error.

Thanks In advance

**Comment by ognjentodic** [comment]
Hello @kamarshad,
The SDK will only work on real device, it doesn't have support for simulator. Thus the problem with compiling/linking.

Also, once you switch to real device, please make sure that the project is properly checked out, using git-lfs. One of the files in the framework is pretty large, so we need to use git-lfs; if you don't have git-lfs setup it you will end up with a small text file instead of the binary file (~168MB) in KeenASR.Framework/Versions/Current/KeenASR. This is not related to your current problem... just heads up.

**Comment by kamarshad** [comment]
Hello @ognjentodic ,

Thank you for your reply. 
Actually, I did not clone(but will clone it mentioned way) the project I just downloaded it and also running the project on real device(iPhone X) but still no luck same build error.

**Comment by ognjentodic** [comment]
Previous error was referencing the simulator; can you please copy/paste the error you are getting when you try to run it on the device.

Also, please do `ls -l KeenASR.Framework/Versions/Current/KeenASR` on the command line and copy/paste the output of the command here. I think git doesn't include files managed by git-lfs in the downloadable zip archive. If that's the case, you'll need to make sure git-lfs is installed properly (you can follow the link from the README file) and then do git checkout.

**Comment by kamarshad** [comment]
Here are the build error logs while I am running the downloaded project for iPhone 7 device.

`Build input file cannot be found: '/Users/mohdkamar/Library/Developer/Xcode/DerivedData/keenasr-swift-poc-glvifghsvbwsqufrainpyozcirde/Build/Products/Debug-iphoneos/keenasr-swift-poc.app/keenasr-swift-poc'`

Also, have a look at the command output.
`-rwxr-xr-x@ 1 mohdkamar  staff  134 Jun 19 12:16 KeenASR.Framework/Versions/Current/KeenASR`

Will be cloning the sample project and will share the final outcome.

**Comment by ognjentodic** [comment]
@kamarshad 
Thanks. Can you please also let me know the version of XCode and report the output of the ls command:
ls -l KeenASR.Framework/Versions/Current/KeenASR

**Comment by kamarshad** [comment]
Hello @ognjentodic  
I am running the project on Xcode 10.1 version and the iPhone 7 device is running on iOS 11.4 version.

Also, have a look at the command output.
`-rwxr-xr-x@ 1 mohdkamar staff 134 Jun 19 12:16 KeenASR.Framework/Versions/Current/KeenASR`

**Comment by ognjentodic** [comment]
@kamarshad, okay, there may be couple of things going on here
1) zip file of project that github provides doesn't include files managed by git-lfs (KeenASR file from the ls command above should be much larger). I also confirmed this by downloading the zip file. By the way, my suggestion to run git checkout will not work for the archive downloaded as zip file since it's not downloaded as a git project. What you need to do instead is: a) install git-lfs, b) clone the project by running `git clone git@github.com:keenresearch/keenasr-swift-poc.git` After that, you can run the ls command again to confirm that the big  file is checked out properly. I would also suggest you remove the old (zip-based) project before doing all of this, to avoid any confusion. You may also want to clear the data in the DerivedData directory (i.e. remove /Users/mohdkamar/Library/Developer/Xcode/DerivedData/keenasr-swift-poc-glvifghsvbwsqufrainpyozcirde folder)

2) There exact error you reported (the last one) is something I have not seen before -- it has to do with XCode build system. I am running the same version of the XCode as you are, and I'm not having any problems building. So, let's first make sure the project is checked out properly, and then when that's the case, and if you are still getting compile/link problems please let me know (there are some online suggestions about using 'Legacy build system' to overcome the type of error you reported, but that's the first time I heard of this problem -- other people have used Swift code without such problem and I am also not experiencing it).

Thanks
Ogi

**Comment by kamarshad** [comment]
Hello @ognjentodic 
Thank you for reply.
I have also cloned the project using `lfs` system and surprisingly got the same error as I mentioned above. The cloned project has four valid architectures `arm64 arm64e armv7 armv7s` as I run the project with the default architecture, below error occured.

 `ld: warning: ignoring file /Users/mohdkamar/Documents/KAMARSHAD_WORKSPACE/PROJECTS/VoiceToSpeech/MainPOC/keenasr-swift-poc/KeenASR.framework/KeenASR, file was built for unsupported file format ( 0x76 0x65 0x72 0x73 0x69 0x6F 0x6E 0x20 0x68 0x74 0x74 0x70 0x73 0x3A 0x2F 0x2F ) which is not the architecture being linked (arm64): /Users/mohdkamar/Documents/KAMARSHAD_WORKSPACE/PROJECTS/VoiceToSpeech/MainPOC/keenasr-swift-poc/KeenASR.framework/KeenASR
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_KIOSResult", referenced from:
      objc-class-ref in ViewController.o
  "_OBJC_CLASS_$_KIOSDecodingGraph", referenced from:
      objc-class-ref in ViewController.o
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_KIOSRecognizer", referenced from:
      objc-class-ref in ViewController.o
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

As I removed `arm64 arm64e` from valid achitecture list and run the project with `armv7 armv7s` architecture getting same build error mentioned in my previous comments.

Here is the command output for the cloned project.

`-rw-r--r--  1 mohdkamar  staff  134 Dec  5 09:24 KeenASR.Framework/Versions/Current/KeenASR`

Looking for your help

**Comment by kamarshad** [comment]
@ognjentodic 
Even my collegue is also facing the same build error.

**Comment by ognjentodic** [comment]
You don't need to remove the arm64 architectures (I would make sure it's back there)

The file KeenASR.Framework/Versions/Current/KeenASR is still not properly checked out though. Its size is 134 bytes where it should be 176406248 bytes.

Did you install git-lfs before cloning the project; it's an extension to git that allows management of large files? If it's installed, you should be able to access git-lfs command on the command line. If you don't have it please install it (README file has a link) , then run git checkout inside the project directory, and then confirm the size of the KeenASR file again.

You could also remove KeenASR.Framework folder completely, then download if from our website, unpack and put in the same place in the project. I highly recommend the original approach (i.e. make sure it's properly checked out via git), since you will need to have git/git-lfs under control (it will come back at you, at some point)

**Comment by kamarshad** [comment]
@ognjentodic 
Yes, I have installed the `lfs` and somehow `git lsf`could not download the file. 
As soon I second-time cloned the project using the `lfs` file downloaded successfully.  Now I am able to run the project without doing architecture changes.

Thanks for your continuous support.

**Comment by ognjentodic** [comment]
@kamarshad Great, I am glad we resolved it. I updated the README file with the note about the zip file potential problems.
